### ISSUE TITLE
Only positive latitude and longitude when importing netcdf in R from paleoView probably wrong projection

### ISSUE THREAD

**Issue by derek-corcoran-barrios** [GlobalEcologyLab/PaleoView#1]
I used the [paleoview][1] software to download some variables from past climate, including the mean temperature from 15000BP-10000BP (I could upload a file on request but its a GB at least).

The main problem is that when I read the raster, it contains only positive latitude and positive longitude. I know from the article that this has a 2.5*2.5 resolution.

## Using Raster

I loaded both the raster and ncdf4 libraries to read it using raster

    library(raster)
    library(ncdf4)

When I read it using the following code 

    r <- raster("mean_temperature-15000BP-10000BP.nc",  varname = "14000BP-13000BP/13300BP")

I get the following info 

    r
    class       : RasterLayer 
    band        : 1  (of  12  bands)
    dimensions  : 72, 144, 10368  (nrow, ncol, ncell)
    resolution  : 1, 1  (x, y)
    extent      : 0.5, 144.5, 0.5, 72.5  (xmin, xmax, ymin, ymax)
    coord. ref. : +proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0 
    names       : Mean.Temperature 
    z-value     : 1 
    zvar        : 14000BP-13000BP/13300BP 

As you see the extent is only positive, but I know it has the data for the whole world, when I plot the map I get the following image:

    plot(r)

[![enter image description here][2]][2]

which clearly shows the patterns expected with the polar circles having extremely low temperatures and the Antarctica being larger that the arctic.

clearly the  +proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0 is wrong here, and I think that if I figure out whats the actual *coord. ref.* I could reproject it and get the raster in the right format

## Using ncdf4

I tried working with the ncdf4 package to try to get more info from the layer, and this is what I did:

    nc <- nc_open("mean_temperature-15000BP-10000BP.nc")
    
After reading the layer using the `nc_open` function I see the names of the variables to try to understand more of the layers, here I show the first 10

    names(nc$var)[1:10]

    [1] "window"                  "width"                   "decimals"                "months"                  "latitudes"               "longitudes"              "15100BP-15000BP/15100BP" "15100BP-15000BP/15099BP"
    [9] "15100BP-15000BP/15098BP" "15100BP-15000BP/15097BP"

So if I keep looking and go to the latitude and longitude names I get:

    ncatt_get(nc, attributes(nc$var)$names[5])
    $units
    [1] "degrees north"

and 

    ncatt_get(nc, attributes(nc$var)$names[6])
    $units
    [1] "degrees east"

Any idea on how to reproject this rasters to get a latitude that goes from -90, 90 and longitude from -180 to 180 that you would expect in a +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0 projections

  [1]: https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.03031
  [2]: https://i.stack.imgur.com/5s91s.jpg

**Comment by seanhaythorne** [comment]
Hi Derek,
Thanks for your feedback.
The paleo-climatic data was encapsulated in ncdf4 files for use with the PaleoView tool, which populates matrices using Python. The latitude and longitude labels were only added for the purpose of describing the data, and are not used by the tool. 
I appreciate that the ncdf4 files could be better adapted for convenient direct use with R, and will keep this in mind for future updates. In the interim, I will investigate how the existing data files can be loaded in R, and will post suggested approaches in the near future.
Please feel free to post any approaches that you derive for the benefit of our research community.
Warm regards,
Sean

**Comment by scbrown86** [comment]
Hi,
I work with the paleoview data every day - all you need to do is flip the data vertically, and define the correct extent. Like Sean says:

> The latitude and longitude labels were only added for the purpose of describing the data, and are not used by the tool

Here's some code that will do exactly that.

```
library(raster)
library(ncdf4)
library(rworldmap)

# get coarse resolution world from rworldmap
sPDF <- getMap()

r <- raster("./mean_temperature-15000BP-10000BP.nc",  
            varname = "14000BP-13000BP/13300BP")
r

# You can see the outline of the continents here, but they are upside down
# E.g. Africa is in the middle
plot(r)
```
![rplot01](https://user-images.githubusercontent.com/23713602/45269977-36c9dc80-b4d6-11e8-8602-6cffe3ee1a34.png)

```
# Needs to be flipped vertically
rFlip <- raster::flip(r, direction = "y")
rFlip
# Now you can clearly see the continents are facing the correct way
plot(rFlip)
```
![rplot](https://user-images.githubusercontent.com/23713602/45270014-d4251080-b4d6-11e8-8316-f32000eb5a10.png)

```
# Need to define a new extent
extent(rFlip) <- extent(c(-180,180,-90,90))
rFlip
plot(rFlip)
plot(sPDF, add = TRUE)
```
![plot](https://user-images.githubusercontent.com/23713602/45269993-7d1f3b80-b4d6-11e8-9dfa-38d89adf33a9.png)

**Comment by seanhaythorne** [comment]
Hi again Derek,
Thanks again for your feedback, which has allowed me to adjust the NetCDF file generation process to be more "R friendly", based on optional aspects of the CF guidelines (http://cfconventions.org/cf-conventions/cf-conventions.html). I will update the climate data files in due course. Meanwhile, the rasters may be generated as follows:
`library(raster)`
`library(ncdf4)`
`nc <- nc_open("PaleoViewData/mean_temperature-15000BP-10000BP.nc")`
`mean_temp_13300BP <- ncvar_get(nc, varid='14000BP-13000BP/13300BP')`
`r_mean_temp_13300BP_Jan <- raster(nrow=72, ncol=144, xmn=-180, xmx=180, ymn=-90, ymx=90)`
`values(r_mean_temp_13300BP_Jan) <- as.vector(mean_temp_13300BP[,,1])`
`r_mean_temp_13300BP_Jul <- raster(nrow=72, ncol=144, xmn=-180, xmx=180, ymn=-90, ymx=90)`
`values(r_mean_temp_13300BP_Jul) <- as.vector(mean_temp_13300BP[,,7])`
`plot(r_mean_temp_13300BP_Jan)`
![image](https://user-images.githubusercontent.com/17334859/45270119-d5593c00-b4dc-11e8-8b54-1689277ec4a3.png)
`plot(r_mean_temp_13300BP_Jul)`
![image](https://user-images.githubusercontent.com/17334859/45270126-f883eb80-b4dc-11e8-8930-59d6ff07d787.png)
Note that the plot you originally posted was up-side-down (note: Northern January cold and heat shadows of land).
Warm regards,
Sean

**Comment by seanhaythorne** [comment]
Thanks Stuart,
I posted my reply before updating the page and seeing your reply. So more than one way is possible.
Cheers,
Sean

**Comment by scbrown86** [comment]
No worries Sean. 

My example can be reduced to two lines - I just made it a bit longer to show the steps.

```
r <- raster::flip(brick("mean_temperature-15000BP-10000BP.nc",  
                         varname = "14000BP-13000BP/13300BP"), "y")
extent(r) <- extent(raster())
```

Also, if you use raster::brick to open the file, you end up with a 12 layer raster stack (one layer for each month) - making it really easy to subset

```
plot(r[[1:6]])
```
![rplot](https://user-images.githubusercontent.com/23713602/45270302-10f30680-b4db-11e8-98ba-7697d5aa3d4b.png)

**Comment by seanhaythorne** [comment]
👍
