### ISSUE TITLE
Data Download error

### ISSUE THREAD

**Issue by pvpoli** [GlobalEcologyLab/PaleoView#2]
Hi,
I am trying to download minimum, mean and maximum temperatures with Paleoview and I'm getting the error (exemple below for minimum temperature):
Could not open minimum_temperature_22000BP-15000BP.nc
Expected climate data NetCDF file at:
http://203.83.208.84/paleodata/
<urlopen error [Errno 10060]
I get the same error no matter the selected interval. 
I'm working on windows 10. Could it be that the adrees is not correct?
Thank you for your help !

**Comment by seanhaythorne** [comment]
Hi,
It appears our original data server is down. I've setup an alternative service:
http://homepage.cs.latrobe.edu.au/shaythorne/paleoview/
This should automatically load into Paleoview's "Download Climate Data" dialog, else you can copy it in:
![image](https://user-images.githubusercontent.com/17334859/48101165-36ea1c80-e27a-11e8-84de-9b7fc95ed7f6.png)
Cheers,
Sean

**Comment by pvpoli** [comment]
Thanks, Sean! It is working fine now. I'll close the issue.
Cheers,
Pedro
