### ISSUE TITLE
Exporting data

### ISSUE THREAD

**Issue by MattiasSealander** [GlobalEcologyLab/PaleoView#4]
Hi,

I have been trying out PaleoView for a bit now. I have downloaded the climate data and been able to view it in the program without any issues. When I try exporting the data as .csv files however I am getting some strange results. 

When attempting to export map grid data for Europe the resulting files (below) are all the same, regardless of what period/-s they cover.

![skarmklipp](https://user-images.githubusercontent.com/44999648/48614336-452cec80-e98e-11e8-8e33-cb91e021f886.JPG)

And if I could also ask, for reference, what should the general format for an exported map grid file look like?

Edit: I tested exporting time series data, and that seems at a first glance to work without any issues.

**Comment by seanhaythorne** [comment]
Hi Mattias,
Please check the generated CSV files using a text editor like notepad. The file contents should contain 72 lines of 144 comma separated values (example attached). 
[grid_data_10BP.csv.txt](https://github.com/GlobalEcologyLab/PaleoView/files/2593343/grid_data_10BP.csv.txt)

If Windows settings are set with a comma (,) as a separator, spreadsheet applications, such as Microsoft Excel should open the file as a 72 by 144 grid (which doesn't appear to be happening in your screen capture).
To set the comma as a separator, go to Control Panel > Region [Formats tab] > Additional settings... and set the list separator to a comma:
![image](https://user-images.githubusercontent.com/17334859/48679500-33915200-ebe5-11e8-8550-8034a579f472.png)

Hope this helps.
Warm regards,
Sean

**Comment by MattiasSealander** [comment]
Hello!

My issue wasn't so much with the formating of the file as it was the appearance that the output data was the same for all periods chosen. I erroneously thought I could scan the data and get a feel for it without properly opening the csv files. Upon closer inspection however (opening it in notepad) I now find that among all the "-9999" there are a couple of actual values, that also are different depending on the period, so it was a mistake on my part.

As you might guess I am a bit new to these types of data, but I take it that the series of "-9999" values are "non-values" in this instance?

![bild](https://user-images.githubusercontent.com/44999648/48691667-a98cbd80-ebd3-11e8-8d19-a701fcee9277.png)

Best regards,
Mattias

**Comment by seanhaythorne** [comment]
Hi Mattias,
Good to see the data is not corrupt at your end. -9999 is the value chosen to represent n/a and region mask values.
Warm regards,
Sean
