### ISSUE TITLE
Error Http 404 page no found 

### ISSUE THREAD

**Issue by lutjanus** [GlobalEcologyLab/PaleoView#5]
Hi:

thank you very much for generating this tool, my question is:
When I try to generate my map of variables for any period of time I get the following error

"Could not open Mean Temperature data for January 145BP. Expected climate data file at: 
http://homepage.cs.latrobe.edu.au/shaythorne/paleoview/T/Trace21_2.5x2.5_145BP.1TA.txt
HTTP Error 404: Not Found"

I've tried it on Mac and Windows and it's the same error

**Comment by seanhaythorne** [comment]
Hi,
This functionality (of sourcing individual data files from the server) is temporarily unavailable due server issues. Please download the data you require (as netCDF files) using the PaleoView's download function (and configure appropriately - see the user guide).
Warm regards,
Sean
