### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by zboraon** [GlobalEcologyLab/PaleoView#7]
Is it possible to install paleoview on a Linux machine, such as on latest Ubuntu LTS?

Thanks in advance.

**Comment by seanhaythorne** [comment]
Hi,
Probably the best way would be to setup a virtual machine (VM) running Windows or Mac OS and install it within the VM.
Cheers,
Sean

**Comment by zboraon** [comment]
Dear Sean,
It would be nice if there were an appimage or java version. But thank you for your immediate reply.
Best,
Bora
